export const SystemCategories = [
  {
    id: 1,
    name: "Alquiler",
    icon: "solar:home-outline",
    type: 2,
  },
  {
    id: 2,
    name: "Alimentos",
    icon: "fluent:food-20-regular",
    type: 2,
  },
  {
    id: 3,
    name: "Transporte",
    icon: "la:bus",
    type: 2,
  },
  {
    id: 4,
    name: "Servicios",
    icon: "material-symbols-light:electrical-services-rounded",
    type: 2,
  },
  {
    id: 5,
    name: "Salud",
    icon: "solar:health-broken",
    type: 2,
  },
  {
    id: 6,
    name: "Educación",
    icon: "basil:book-outline",
    type: 2,
  },
  {
    id: 7,
    name: "Entretenimiento",
    icon: "gg:games",
    type: 2,
  },
  {
    id: 8,
    name: "Ahorros",
    icon: "material-symbols:savings-outline-rounded",
    type: 2,
  },
  {
    id: 9,
    name: "Ropa",
    icon: "fluent-emoji-high-contrast:running-shoe",
    type: 2,
  },
  {
    id: 10,
    name: "Viajes",
    icon: "mynaui:aeroplane",
    type: 2,
  },
  {
    id: 11,
    name: "Salario",
    icon: "fluent:money-20-regular",
    type: 1,
  },
  {
    id: 12,
    name: "Nómina",
    icon: "ic:baseline-account-balance-wallet",
    type: 2,
  },
  {
    id: 13,
    name: "Alquiler de Oficina",
    icon: "ic:outline-business-center",
    type: 2,
  },
  {
    id: 14,
    name: "Materias Primas",
    icon: "mdi:cube-outline",
    type: 2,
  },
  {
    id: 15,
    name: "Marketing y Publicidad",
    icon: "mdi:bullhorn-outline",
    type: 2,
  },
  {
    id: 16,
    name: "Tecnología e Informática",
    icon: "mdi:desktop-classic",
    type: 2,
  },
  {
    id: 17,
    name: "Viajes de Negocios",
    icon: "mdi:airplane-takeoff",
    type: 2,
  },
  {
    id: 18,
    name: "Servicios Profesionales",
    icon: "mdi:briefcase-outline",
    type: 2,
  },
  {
    id: 19,
    name: "Seguros",
    icon: "mdi:shield-outline",
    type: 2,
  },
  {
    id: 20,
    name: "Impuestos y Licencias",
    icon: "mdi:file-document-outline",
    type: 2,
  },
  {
    id: 21,
    name: "Capacitación y Desarrollo",
    icon: "mdi:school-outline",
    type: 2,
  },
];
