import { differenceInDays } from "date-fns";
import { NotificationInput } from "./types";
import { setExternalId } from "./setExternalId";

export const NOTIFICATIONS = {
  transaction: {
    created: (data: NotificationInput<"transaction.created">) => ({
      bookId: data?.bookId,
      userId: data?.userId,
      type: "TRANSACTION_CREATED",
      title: "Transacción registrada",
      message: data.category
        ? `Registraste $${data.amount} en ${data.category?.name}.`
        : `Registraste $${data.amount}.`,
      link: `/transactions/${data.id}`,
      metadata: { transactionId: data.id },
      externalId: setExternalId("transaction", data.id, "created"),
    }),
    updated: (data: NotificationInput<"transaction.edited">) => ({
      bookId: data.bookId,
      userId: data.userId,
      type: "TRANSACTION_UPDATED",
      title: "Transacción actualizada",
      message: `Actualizaste tu transacción de <strong>$${data.amount.toLocaleString()}</strong>.`,
      link: `/transactions/${data.id}`,
      metadata: { transactionId: data.id },
      externalId: setExternalId("transaction", data.id, "edited"),
    }),
    nearDeadline: (data: NotificationInput<"transaction.nearDeadline">) => ({
      bookId: data.bookId,
      userId: data.userId,
      type: "TRANSACTION_NEAR_DEADLINE",
      title: "¡Transacción por vencer!",
      message: `Tu transacción de $${data.amount.toLocaleString()} ${data.category?.name ? `en ${data.category.name}` : ""} está por vencer.`,
      link: `/transactions/${data.id}`,
      metadata: { transactionId: data.id },
      externalId: setExternalId("transaction", data.id, "nearDeadline"),
    }),
    lastDay: (data: NotificationInput<"transaction.lastDay">) => ({
      bookId: data.bookId,
      userId: data.userId,
      type: "TRANSACTION_LAST_DAY",
      title: "¡Último día para la transacción!",
      message: `Tu transacción programada por <strong>${data.amount.toLocaleString()}</strong> vencerá hoy.`,
      link: `/transactions/${data.id}`,
      metadata: { transactionId: data.id },
      externalId: setExternalId("transaction", data.id, "lastDay"),
    }),
    success: (data: NotificationInput<"transaction.success">) => ({
      bookId: data.bookId,
      userId: data.userId,
      type: "TRANSACTION_SUCCESS",
      title: "¡Transacción Ejecutada!",
      message: `Tu transacción programada de <strong>$${data.amount.toLocaleString()}</strong>. fue ejecutada.`,
      link: `/transactions/${data.id}`,
      metadata: { transactionId: data.id },
      externalId: setExternalId("transaction", data.id, "success"),
    }),
    expired: (data: NotificationInput<"transaction.expired">) => ({
      bookId: data.bookId,
      userId: data.userId,
      type: "TRANSACTION_EXPIRED",
      title: "¡Transacción Expirada!",
      message: `Tu transacción de <strong>$${data.amount.toLocaleString()}</strong> ${data.category?.name ? `en <strong>${data.category.name}</strong>` : ""} ha expirado.`,
      link: `/transactions/${data.id}`,
      metadata: { transactionId: data.id },
      externalId: setExternalId("transaction", data.id, "expired"),
    }),
  },
  movement: {
    lastDay: (data: NotificationInput<"movement:lastDay">) => ({
      bookId: data.bookId,
      userId: data.userId,
      type: "MOVEMENT_LAST_DAY",
      title: "¡Último día para el movimiento!",
      message: `Tu movimiento <strong>"${data.name}"</strong> por <strong>${data.amount.toLocaleString()}</strong> vencerá hoy.`,
      link: `/movements/${data.id}`,
      metadata: { movementId: data.id },
      externalId: setExternalId("movement", data.id, "lastDay"),
    }),
    nearDeadline: (data: NotificationInput<"movement:nearDeadline">) => ({
      bookId: data.bookId,
      userId: data.userId,
      type: "MOVEMENT_REMINDER",
      title: "Movimiento por vencer",
      message: `Tu movimiento <strong>"${data.name}"</strong> vencerá en ${differenceInDays(data.next_ocurrence, new Date())} días.`,
      link: `/movements/${data.id}`,
      metadata: { movementId: data.id },
      externalId: setExternalId("movement", data.id, "nearDeadline"),
    }),
    executed: (data: NotificationInput<"movement:executed">) => ({
      bookId: data.bookId,
      userId: data.userId,
      type: "MOVEMENT_EXECUTED",
      title: "Movimiento Ejecutado",
      message: `Tu movimiento <strong>"${data.name}"</strong> fue realizado.`,
      link: `/movements/${data.id}`,
      metadata: { movementId: data.id },
      externalId: setExternalId("movement", data.id, "executed"),
    }),
    expired: (data: NotificationInput<"movement:expired">) => ({
      bookId: data.bookId,
      userId: data.userId,
      type: "MOVEMENT_EXPIRED",
      title: "¡Movimiento expirado!",
      message: `Tu movimiento <strong>"${data.name}"</strong> ha expirado`,
      link: `/movements/${data.id}`,
      metadata: { movementId: data.id },
      externalId: setExternalId("movement", data.id, "expired"),
    }),
    success: (data: NotificationInput<"movement:success">) => ({
      bookId: data.bookId,
      userId: data.userId,
      type: "MOVEMENT_SUCCESS",
      title: "¡Movimiento ejecutado!",
      message: `Tu movimiento <strong>"${data.name}"</strong> fue ejecutado.`,
      link: `/movements/${data.id}`,
      metadata: { movementId: data.id },
      externalId: setExternalId("movement", data.id, "success"),
    }),
    error: (data: NotificationInput<"movement:error">, error: string) => ({
      bookId: data.bookId,
      userId: data.userId,
      type: "MOVEMENT_ERROR",
      title: "Error en movimiento recurrente",
      message: `No se pudo ejecutar el movimiento "${data.name}".`,
      metadata: { movementId: data.id, error },
      externalId: setExternalId("movement", data.id, "error"),
    }),
  },
  //   goal: {
  //     created: (data: NotificationInput<"goal.created">) => ({
  //       userId: data?.userId,
  //       type: "GOAL_CREATED",
  //       title: "Nueva meta creada",
  //       message: `Iniciaste la meta "${data?.name}" por $${data?.goal}.`,
  //       link: `/goals/${data?.id}`,
  //       metadata: { goalId: data?.id },
  //     }),
  //     progress: (data: GoalsIncludes) => ({
  //       userId: data?.userId,
  //       type: "GOAL_PROGRESS",
  //       title: "Progreso en tu meta",
  //       message: `Has avanzado $${data.goal} en tu meta "${data.name}".`,
  //       link: `/goals/${data.id}`,
  //       metadata: { goalId: data.id, amount: data.goal },
  //     }),
  //     completed: (data: GoalsIncludes) => ({
  //       userId: data.userId,
  //       type: "GOAL_COMPLETED",
  //       title: "¡Meta alcanzada!",
  //       message: `Completaste tu meta "${data.name}".`,
  //       link: `/goals/${data.id}`,
  //       metadata: { goalId: data.id },
  //     }),
  //   },
  // budget: {
  //   initialized: (data: ) => ({
  //     userId: data.userId,
  //     type: "BUDGET_INITIALIZED",
  //     title: "Presupuesto mensual listo",
  //     message: `Tu presupuesto de ${data.monthName} ha sido generado con base en tus movimientos y transacciones programadas.`,
  //     link: `/app/budget/${data.budget.id}`,
  //     metadata: { budgetId: data.budget.id, month: data.monthName },
  //   }),
  //   // limitReached: (data) => ({
  //   //   userId: data.userId,
  //   //   type: "BUDGET_LIMIT_REACHED",
  //   //   title: "¡Presupuesto agotado!",
  //   //   message: `Has gastado el 100% de tu presupuesto mensual.`,
  //   //   link: `/app/budget/${data.budget.id}`,
  //   //   metadata: { budgetId: data.budget.id },
  //   // }),
  //   // nearLimit: (data) => ({
  //   //   userId: data.userId,
  //   //   type: "BUDGET_NEAR_LIMIT",
  //   //   title: "Presupuesto casi completo",
  //   //   message: `Ya utilizaste el ${data.percentage}% de tu presupuesto de ${data.monthName}.`,
  //   //   link: `/app/budget/${data.budget.id}`,
  //   //   metadata: { budgetId: data.budget.id, percentage: data.percentage },
  //   // }),
  //   // balanceProjectedNegative: (data) => ({
  //   //   userId: data.userId,
  //   //   type: "BUDGET_NEGATIVE_PROJECTION",
  //   //   title: "Proyección de balance negativa",
  //   //   message: `Tu proyección al final del mes es negativa: $${data.projectedBalance}. Revisa tus gastos.`,
  //   //   link: `/app/budget/${data.budget.id}`,
  //   //   metadata: {
  //   //     budgetId: data.budget.id,
  //   //     projectedBalance: data.projectedBalance,
  //   //   },
  //   // }),
  //   // balanceImproved: (data) => ({
  //   //   userId: data.userId,
  //   //   type: "BUDGET_IMPROVED_PROJECTION",
  //   //   title: "¡Tu balance ha mejorado!",
  //   //   message: `Tu nuevo balance proyectado es de $${data.projectedBalance}. Vas por buen camino.`,
  //   //   link: `/app/budget/${data.budget.id}`,
  //   //   metadata: {
  //   //     budgetId: data.budget.id,
  //   //     projectedBalance: data.projectedBalance,
  //   //   },
  //   // }),
  //   // summaryReminder: (data) => ({
  //   //   userId: data.userId,
  //   //   type: "BUDGET_MONTHLY_REMINDER",
  //   //   title: "Resumen de fin de mes",
  //   //   message: `Falta poco para acabar el mes. Has gastado $${data.spent} y tu balance actual es $${data.balance}.`,
  //   //   link: `/app/budget/${data.budget.id}`,
  //   //   metadata: {
  //   //     budgetId: data.budget.id,
  //   //     spent: data.spent,
  //   //     balance: data.balance,
  //   //   },
  //   // }),
  //   // success: (data) => ({
  //   //   userId: data.userId,
  //   //   type: "BUDGET_SUCCESS",
  //   //   title: "¡Presupuesto cumplido!",
  //   //   message: `Finalizaste el mes dentro del presupuesto. ¡Buen trabajo!`,
  //   //   link: `/app/budget/${data.budget.id}`,
  //   //   metadata: { budgetId: data.budget.id },
  //   // }),
  // },
  //   system: {
  //     weeklyReminder: (data) => ({
  //       userId: data.userId,
  //       type: "WEEKLY_SUMMARY",
  //       title: "Resumen semanal disponible",
  //       message: `Tu resumen de gastos de la semana ya está disponible.`,
  //       link: `/app/reports/weekly`,
  //     }),
  //   },
} as const;
